[tool.black]
line-length = 100
target-version = ["py311"]

[tool.ruff]
line-length = 100
exclude = [
  "alembic",
  "alembic/versions",
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[tool.ruff.lint]
select = ["E", "F", "I", "B", "UP"]
ignore = ["E501", "F401"]

[tool.pytest.ini_options]
testpaths = ["tests"]
norecursedirs = [
  "alembic",
  "alembic/versions",
]
